### ISSUE TITLE
Scope not closed during tests

### ISSUE THREAD

**Issue by mihau** [opentracing/opentracing-python#117]
https://github.com/opentracing/opentracing-python/blob/1d495f7b1c89e3577c0ce4911ed2962c8dcf1482/opentracing/harness/api_check.py#L73

In this test a scope is being opened, but it's left unclosed. This might cause issues, since an active scope will persist in thread local storage even though a new tracer is created, causing another [test](https://github.com/opentracing/opentracing-python/blob/1d495f7b1c89e3577c0ce4911ed2962c8dcf1482/opentracing/harness/api_check.py#L324) to fail.

This can be treated as an issue with tests, or a broader one - the key for active scope in thread local storage being same for all tracers created in that thread.

**Comment by yurishkuro** [comment]
Fixed by #97

**Comment by yurishkuro** [comment]
@mihau #97 was merged last August, but this ticket opened 12 days ago? I'm confused.

**Comment by mihau** [comment]
Sorry for that, I forgot about the fix , and used `2.0.0` by mistake, my bad. Closing
