### ISSUE TITLE
TypeError in text_propagator

### ISSUE THREAD

**Issue by logileifs** [opentracing/opentracing-python#133]
https://github.com/opentracing/opentracing-python/blob/master/opentracing/mocktracer/text_propagator.py#L58 I get an error here when using the MockTracer with my Starlette tests, it's trying to compare bytes with string.

proposed fix:
```
elif k.startswith(prefix_baggage.encode()):
        baggage[k[len(prefix_baggage):]] = v
```

**Comment by yurishkuro** [comment]
which are bytes and which is string? what python version is this for? we already have CI for various Python versions, why doesn't that issue come up there?

**Comment by logileifs** [comment]
I am using [starlette opentracing](https://github.com/acidjunk/starlette-opentracing) and there all headers are being encoded as bytes which then get compared to `prefix_baggage = 'ot-baggage-'` which is a string. I guess that's a bug in the starlette opentracing package because when I remove the encode there everything works as expected.
Sorry about the misunderstanding
