### ISSUE TITLE
logging hander

### ISSUE THREAD

**Issue by kornerc** [opentracing/opentracing-python#140]
I am currently implementing an opentracing handler for the `logging` library.
It propagates logging calls to `log_kv` such that Python logging can be used in opentracing.
When a logging method is called it tries to get the current scope with ` scope = tracer.scope_manager.active`.
When the scope is not None (so when a scope is active) it forwards the logging arguments to log_kv.

I want to publish this piece of code because it might be useful also to others.
Should I create a pull request so that this functionality can be added to this repo or do you prefer me to create my own repo which includes only the opentracing handler for the logging library?

This is a simplified version of the code.
```python
import logging

from opentracing import Tracer

class OpenTracingHandler(logging.Handler):
    def __init__(self, tracer: Tracer):
        super().__init__()

        self._tracer = tracer

    def emit(self, record: logging.LogRecord):
        scope = self._tracer.scope_manager.active

        if scope is None:
            return

        span = scope.span

        span.log_kv({'msg': record.msg})

tracer: Tracer = # initialize the tracer

logger = logging.getLogger('Example')
logger.addHandler(OpenTracingHandler(tracer=tracer))

with tracer.start_active_span('foo') as scope:
    logging.warning('This can be seen in opentracing')
```

**Comment by yurishkuro** [comment]
I recommend creating your own project and adding it to opentracing.io/registry. If you wish, you can put the project into opentracing-contrib org, or just keep it under your own account.

**Comment by kornerc** [comment]
Okay thanks for your quick reply!
I'll make my own project and can migrate it later on to opentracing-contrib org when it's ready.
