### ISSUE TITLE
Build a wheel distribution

### ISSUE THREAD

**Issue by Lawouach** [opentracing/opentracing-python#155]
Hey folks,

Thanks for this great project. Would it be possible to distribute also as a wheel? This is quite handy when it comes to packaging dependencies afterwards. 

This may help:
https://github.com/pypa/cibuildwheel

Best,

**Comment by yurishkuro** [comment]
The library is deprecated, so -- no.

Also, it seems wheel is to a large degree superfluous since this lib is tiny and there isn't much difference between installing a wheel or the sdist.

**Comment by Lawouach** [comment]
Thanks for the feedback.

That said, the size is irrelevant to the distribution limitation of not offering wheels. Anyway since it's deprecated no point arguing.
