### ISSUE TITLE
Implementations *must* raise UnsupportedFormatException on unknown formats

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-python#30]
Consider this code

```
    try:
        carrier = {}
        span.tracer.inject(span, SOME_CUSTOM_FORMAT, carrier)
        do_something(carrier)
    except opentracing.UnsupportedFormatException:
        pass  # it's possible tracer does not support out custom format
    except:
        log.exception('Failed to inject tracing span into headers')
        metric.incCounter()
```

Without a mandate for the tracers (including the Noop tracer) to return an exception on unknown format there is no way in the code to know if the situation is legitimate (i.e. tracer does not support given custom format) or a genuine error (bad context propagation or what not).

**Comment by bensigelman** [comment]
+1 to the basic issue here.

@yurishkuro what do you think about the corrupted carrier stuff, though? I have some anxiety about what's essentially monitoring code throwing exceptions (that users may not be catching) when tracing data is in a bad state. I would be fine with returning a bool or an error (perhaps as an output param), but actually raising an exception could be pretty disastrous in some cases.
Thoughts?

**Comment by yurishkuro** [comment]
I didn't like throwing exceptions myself, but someone claimed that this is the idiomatic way in Python. The only other thing we could've done was to adopt Go style and return an error constant that the caller can check.

But I am not too concerned with that. Malformed carriers are either a sign of chopped up requests, or a misconfiguration. The former is also a sign of some misconfiguration. So in that case it doesn't seem too bad if we throw exception. And ultimately it's a bad instrumentation code if it doesn't catch and handle exceptions.
