### ISSUE TITLE
the comment is missleading, python has references and values

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [opentracing/opentracing-python#55]
https://github.com/opentracing/opentracing-python/blob/a86ee3d49df569691433e0ce0101105638ca8be8/opentracing/__init__.py#L36-L39

in order to provide a more correct api, expose the tracing creating and tracer management apis not as a global with a comment to "replace"
but rather as a collection of module scope functions that fetch the right tracer

the global variable is pretty much asking for trouble
see the stdlib logging module and logbook for structural examples

**Comment by carlosalberto** [comment]
Addressed by #95
