### ISSUE TITLE
futures or future?

### ISSUE THREAD

**Issue by nehaljwani** [opentracing/opentracing-python#60]
In setup.py, we have:
```
    install_requires=[
        'futures',
    ],
```
Was it actually meant to be 'future' and not 'futures'?

I don't see `concurrent.futures` being used anywhere. But I do see `_future_` being used in the code.

**Comment by yurishkuro** [comment]
```
jaeger_client/ioloop_util.py:18:from concurrent.futures import Future
jaeger_client/local_agent_net.py:22:from concurrent.futures import Future
jaeger_client/reporter.py:24:from concurrent.futures import Future
```

**Comment by nehaljwani** [comment]
jaeger_client already depends on futures, as I can see at https://github.com/jaegertracing/jaeger-client-python/blob/3.6.1/setup.py#L38 . But why does opentracing-python have to depend on it?

**Comment by yurishkuro** [comment]
Oh, sorry, I didn't pay attention to the repo. Yes, it looks like this dependency should be removed.
