### ISSUE TITLE
Tags are not up-to-date in the latest release

### ISSUE THREAD

**Issue by mohabusama** [opentracing/opentracing-python#61]
``ext.tags`` in version 1.2.2 is outdated compared to master. Any plans for releasing a new version with updated tags?

**Comment by SEJeff** [comment]
See #65 for the 2.0 release. This isn't an issue and should be closed.

**Comment by carlosalberto** [comment]
Hey @mohabusama now that we have released 2.0 this should be fixed. Please re-open in case there's still a pending related problem ;)
