### ISSUE TITLE
Span does not set error tag if `__exit__` is called with an exception

### ISSUE THREAD

**Issue by nziebart** [opentracing/opentracing-python#72]
It seems like we'd want to do the following if a span is closed exceptionally, given that we're already logging the exception to the span:
```
def __exit__(self, exc_type, exc_val, exc_tb):
    if exc_type:
        self.set_tag(tags.ERROR, True)
    ...
```

If others agree I can open a PR

**Comment by yurishkuro** [comment]
is it going to be a breaking change?

**Comment by nziebart** [comment]
Hmm, I have not used opentracing very extensively but:
- it does not seem like a behavioral break; a user would expect this tag to be set in this case
- it MIGHT be a functional break if the user is already setting this tag manually (actually, I am doing so in my project). depending on the implementation it could result in duplicate tags, which may cause an issue

**Comment by yurishkuro** [comment]
NVM I was thinking it would be a different signature. 

The existing implementation already logs the exception. But setting the error tag would not be correct behavior, because an exception does not mean the operation was in error (maybe it has retries).

**Comment by nziebart** [comment]
But if a span is closed in response to an exception, any retry logic would have to initiate a new span. Thus it seems like the closed span would indeed represent a failed operation

**Comment by nziebart** [comment]
I see that point but I guess I am questioning the validity of it. You have a with block that was aborted due to an uncaught exception. If you do not want that to be marked as an error, you should catch the exception. Most people will expect this to show up in the UI as an error.

You can say that this isn’t the responsibility of the default impl, but then why is it even logging the exception? It should either do both or neither IMO

**Comment by yurishkuro** [comment]
@nziebart I am leaning towards agreeing with your argument. Even though it may not be always correct to mark the span as error when it's used in `with span` structure, it's probably correct in the majority of cases, and in rare cases where it's not an error people can use try/except explicitly, without the context manager.

**Comment by yurishkuro** [comment]
cc @carlosalberto @tedsuo

**Comment by carlosalberto** [comment]
>  Even though it may not be always correct to mark the span as error when it's used in with span structure, it's probably correct in the majority of cases

I think this is accurate, indeed. I only remember handling errors as non-fatal for `requests`, as they do retries. For the rest, yes, it makes sense.

**Comment by yurishkuro** [comment]
+1

**Comment by carlosalberto** [comment]
Hey @nziebart if you are still around, feel free to cook a PR yourself ;)

(Else I will do it myself in a few days ;) )

**Comment by carlosalberto** [comment]
Closing this one via #101
